api_platform:
    title: 'API TEACHRS'
    description: 'API test technique février 2021'
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]